# Generated by Django 4.1.7 on 2023-03-13 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=75)),
                ('formato', models.CharField(max_length=75)),
                ('data', models.DateField()),
                ('image', models.FileField(upload_to='images/')),
                ('fk_banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.banda')),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('autores', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='musics/')),
                ('image', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=25)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Own',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.banda')),
                ('fk_musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.musico')),
            ],
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Toca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.instrumento')),
                ('fk_musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.musico')),
            ],
        ),
        migrations.CreateModel(
            name='Produz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_disco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.disco')),
                ('fk_produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.produtor')),
            ],
        ),
        migrations.CreateModel(
            name='Participa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.musica')),
                ('fk_own', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.own')),
            ],
        ),
        migrations.CreateModel(
            name='Esta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.banda')),
                ('fk_musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.musico')),
            ],
        ),
        migrations.AddField(
            model_name='disco',
            name='fk_musico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.musico'),
        ),
        migrations.CreateModel(
            name='Aparece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_disco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.disco')),
                ('fk_musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.musica')),
            ],
        ),
    ]
