# Generated by Django 4.1.7 on 2023-03-14 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disco',
            name='fk_banda',
        ),
        migrations.RemoveField(
            model_name='disco',
            name='fk_musico',
        ),
        migrations.RemoveField(
            model_name='esta',
            name='fk_banda',
        ),
        migrations.RemoveField(
            model_name='esta',
            name='fk_musico',
        ),
        migrations.RemoveField(
            model_name='own',
            name='fk_banda',
        ),
        migrations.RemoveField(
            model_name='own',
            name='fk_musico',
        ),
        migrations.RemoveField(
            model_name='participa',
            name='fk_musica',
        ),
        migrations.RemoveField(
            model_name='participa',
            name='fk_own',
        ),
        migrations.RemoveField(
            model_name='produz',
            name='fk_disco',
        ),
        migrations.RemoveField(
            model_name='produz',
            name='fk_produtor',
        ),
        migrations.RemoveField(
            model_name='toca',
            name='fk_instrumento',
        ),
        migrations.RemoveField(
            model_name='toca',
            name='fk_musico',
        ),
        migrations.DeleteModel(
            name='Aparece',
        ),
        migrations.DeleteModel(
            name='Banda',
        ),
        migrations.DeleteModel(
            name='Disco',
        ),
        migrations.DeleteModel(
            name='Esta',
        ),
        migrations.DeleteModel(
            name='Instrumento',
        ),
        migrations.DeleteModel(
            name='Musica',
        ),
        migrations.DeleteModel(
            name='Musico',
        ),
        migrations.DeleteModel(
            name='Own',
        ),
        migrations.DeleteModel(
            name='Participa',
        ),
        migrations.DeleteModel(
            name='Produtor',
        ),
        migrations.DeleteModel(
            name='Produz',
        ),
        migrations.DeleteModel(
            name='Toca',
        ),
    ]
