# Generated by Django 4.1.7 on 2023-03-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='file',
            field=models.FileField(upload_to='songs/'),
        ),
    ]
