# Generated by Django 4.1.7 on 2023-03-26 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_musica_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='fk_banda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.banda'),
        ),
        migrations.AlterField(
            model_name='disco',
            name='fk_musico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.musico'),
        ),
        migrations.AlterField(
            model_name='own',
            name='fk_banda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.banda'),
        ),
        migrations.AlterField(
            model_name='own',
            name='fk_musico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.musico'),
        ),
    ]
