# Generated by Django 4.1.7 on 2023-04-04 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_disco_fk_banda_alter_disco_fk_musico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='own',
            name='fk_banda',
        ),
        migrations.RemoveField(
            model_name='own',
            name='fk_musico',
        ),
        migrations.AlterField(
            model_name='banda',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='members.own'),
        ),
        migrations.AlterField(
            model_name='musico',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='members.own'),
        ),
        migrations.AlterField(
            model_name='own',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
