# Generated by Django 4.1.7 on 2023-05-10 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_own_fk_banda_remove_own_fk_musico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disco',
            name='image',
        ),
    ]
