# Generated by Django 4.1.7 on 2023-05-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_remove_disco_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='participa',
            field=models.ManyToManyField(to='members.own'),
        ),
        migrations.DeleteModel(
            name='Participa',
        ),
    ]
