# Generated by Django 4.1.7 on 2023-05-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_musica_participa_delete_participa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esta',
            name='fk_banda',
        ),
        migrations.RemoveField(
            model_name='esta',
            name='fk_musico',
        ),
        migrations.RemoveField(
            model_name='produz',
            name='fk_disco',
        ),
        migrations.RemoveField(
            model_name='produz',
            name='fk_produtor',
        ),
        migrations.RemoveField(
            model_name='toca',
            name='fk_instrumento',
        ),
        migrations.RemoveField(
            model_name='toca',
            name='fk_musico',
        ),
        migrations.RemoveField(
            model_name='disco',
            name='fk_banda',
        ),
        migrations.RemoveField(
            model_name='disco',
            name='fk_musico',
        ),
        migrations.AddField(
            model_name='disco',
            name='disco_banda',
            field=models.ManyToManyField(to='members.banda'),
        ),
        migrations.AddField(
            model_name='disco',
            name='disco_musico',
            field=models.ManyToManyField(to='members.musico'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='toca',
            field=models.ManyToManyField(to='members.musico'),
        ),
        migrations.AddField(
            model_name='musica',
            name='aparece',
            field=models.ManyToManyField(to='members.disco'),
        ),
        migrations.AddField(
            model_name='musico',
            name='esta',
            field=models.ManyToManyField(to='members.banda'),
        ),
        migrations.DeleteModel(
            name='Aparece',
        ),
        migrations.DeleteModel(
            name='Esta',
        ),
        migrations.DeleteModel(
            name='Produz',
        ),
        migrations.DeleteModel(
            name='Toca',
        ),
    ]
