# Generated by Django 4.1.7 on 2023-05-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_remove_esta_fk_banda_remove_esta_fk_musico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='toca',
        ),
        migrations.AddField(
            model_name='musico',
            name='toca',
            field=models.ManyToManyField(to='members.instrumento'),
        ),
    ]
