# Generated by Django 4.1.7 on 2023-05-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_remove_instrumento_toca_musico_toca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musica',
            name='participa',
        ),
        migrations.AddField(
            model_name='musica',
            name='participa_Banda',
            field=models.ManyToManyField(to='members.banda'),
        ),
        migrations.AddField(
            model_name='musica',
            name='participa_Musico',
            field=models.ManyToManyField(to='members.musico'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='musico',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Own',
        ),
    ]
