# Generated by Django 4.1.7 on 2023-05-31 00:30

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_banda_id_alter_musico_id'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='disco',
            trigger=pgtrigger.compiler.Trigger(name='must_have_disco_musico_or_disco_banda', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.titulo = NEW.titulo; RETURN NEW;', hash='e4361479f7b11d240c5e96cee6095c3d03ba075a', operation='UPDATE OR INSERT', pgid='pgtrigger_must_have_disco_musico_or_disco_banda_19906', table='members_disco', when='BEFORE')),
        ),
    ]
