# Generated by Django 4.1.7 on 2023-05-31 00:40

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_remove_disco_must_have_disco_musico_or_disco_banda_and_more'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='musica',
            trigger=pgtrigger.compiler.Trigger(name='must_have_particpa_Musico_or_participa_Banda', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n\t\t\t\t\tIF (NEW.participa_Musico != NULL OR NEW.participa_Banda) THEN\n\t\t\t\t\t\tRETURN NEW;\n\t\t\t\t\tEND IF;\n\t\t\t\t', hash='6887d7c2ee1c78472387079ab523be205ca23901', operation='UPDATE OR INSERT', pgid='pgtrigger_must_have_particpa_musico_or_participa_banda_97de8', table='members_musica', when='BEFORE')),
        ),
    ]
