# Generated by Django 4.1.7 on 2023-05-31 01:11

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_musica_must_have_particpa_musico_or_participa_banda'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='banda',
            trigger=pgtrigger.compiler.Trigger(name='must_have_different_name', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n\t\t\t\t\tIF (SELECT COUNT(*) FROM members_banda WHERE NOME = NEW.nome == 0) THEN\n\t\t\t\t\t\tRETURN NEW;\n\t\t\t\t\tEND IF;\n\t\t\t\t', hash='e0d3e2f14ce815863e2015bb62eb060416e28094', operation='UPDATE OR INSERT', pgid='pgtrigger_must_have_different_name_fce46', table='members_banda', when='BEFORE')),
        ),
    ]
