# Generated by Django 4.1.7 on 2023-05-31 01:15

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_banda_must_have_different_name'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='banda',
            name='must_have_different_name',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='banda',
            trigger=pgtrigger.compiler.Trigger(name='banda_must_have_different_name', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n\t\t\t\t\tIF (SELECT COUNT(*) FROM members_banda WHERE NOME = NEW.nome == 0) THEN\n\t\t\t\t\t\tRETURN NEW;\n\t\t\t\t\tEND IF;\n\t\t\t\t', hash='e15a606d74e33fcb54de6ed85e75e64abfeb694d', operation='UPDATE OR INSERT', pgid='pgtrigger_banda_must_have_different_name_e7880', table='members_banda', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='instrumento',
            trigger=pgtrigger.compiler.Trigger(name='instrumento_must_have_different_name', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n\t\t\t\t\tIF (SELECT COUNT(*) FROM members_instrumento WHERE NOME = NEW.nome == 0) THEN\n\t\t\t\t\t\tRETURN NEW;\n\t\t\t\t\tEND IF;\n\t\t\t\t', hash='85bf972dcf6cfd96391104a8ec877509fac8a1dd', operation='UPDATE OR INSERT', pgid='pgtrigger_instrumento_must_have_different_name_18cb6', table='members_instrumento', when='BEFORE')),
        ),
    ]
