# Generated by Django 4.1.7 on 2023-05-31 01:24

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_remove_banda_must_have_different_name_and_more'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='musico',
            trigger=pgtrigger.compiler.Trigger(name='musico_must_have_different_name_and_telefone', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n\t\t\t\t\tIF (SELECT COUNT(*) FROM members_musico WHERE NOME = NEW.nome AND TELEFONE =  NEW.telefone  == 0) THEN\n\t\t\t\t\t\tRETURN NEW;\n\t\t\t\t\tEND IF;\n\t\t\t\t', hash='fe3458d20fa8fa274df14cc4a2a538cff3dbc479', operation='UPDATE OR INSERT', pgid='pgtrigger_musico_must_have_different_name_and_telefone_326d4', table='members_musico', when='BEFORE')),
        ),
    ]
