# Generated by Django 4.1.7 on 2023-05-31 01:27

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_musico_musico_must_have_different_name_and_telefone'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='produtor',
            trigger=pgtrigger.compiler.Trigger(name='produtor_must_have_different_name', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n\t\t\t\t\tIF (SELECT COUNT(*) FROM members_produtor WHERE NOME = NEW.nome == 0) THEN\n\t\t\t\t\t\tRETURN NEW;\n\t\t\t\t\tEND IF;\n\t\t\t\t', hash='60cabb030635534e865d5ece17be042e15aa18f2', operation='UPDATE OR INSERT', pgid='pgtrigger_produtor_must_have_different_name_4c1d7', table='members_produtor', when='BEFORE')),
        ),
    ]
