# Generated by Django 4.1.7 on 2023-05-31 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_produtor_produtor_must_have_different_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='produzido',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.produtor'),
        ),
    ]
