# Generated by Django 4.1.7 on 2023-05-31 01:58

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_remove_produtor_produtor_must_have_different_name_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='produtor',
            name='produtor_must_have_different_name',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='produtor',
            trigger=pgtrigger.compiler.Trigger(name='produtor_must_have_different_namo', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n\t\t\t\t\tIF ((SELECT COUNT(*) FROM members_produtor WHERE NOME = NEW.nome) < 1) THEN\n\t\t\t\t\t\tRETURN NEW;\n\t\t\t\t\tEND IF;\n\t\t\t\t', hash='946ff792c8eeb648de7db863609aa66343d141fe', operation='UPDATE OR INSERT', pgid='pgtrigger_produtor_must_have_different_namo_c2880', table='members_produtor', when='BEFORE')),
        ),
    ]
