# Generated by Django 4.1.7 on 2023-05-31 02:05

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_remove_banda_banda_must_have_different_name_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='musico',
            name='musico_must_have_different_name_and_telefone',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='musico',
            trigger=pgtrigger.compiler.Trigger(name='musico_must_have_different_name_and_telefone', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n\t\t\t\t\tIF ((SELECT COUNT(*) FROM members_musico WHERE NOME = NEW.nome OR TELEFONE =  NEW.telefone) < 1) THEN\n\t\t\t\t\t\tRETURN NEW;\n\t\t\t\t\tEND IF;\n\t\t\t\t', hash='d4504a82613101e525ff2f6a9dbb8b3f08be52e1', operation='UPDATE OR INSERT', pgid='pgtrigger_musico_must_have_different_name_and_telefone_326d4', table='members_musico', when='BEFORE')),
        ),
    ]
