# Generated by Django 4.1.7 on 2023-05-31 02:29

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_remove_musico_musico_must_have_different_name_and_telefone_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='musica',
            name='must_have_particpa_Musico_or_participa_Banda',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='musica',
            trigger=pgtrigger.compiler.Trigger(name='must_have_particpa_Musico_or_participa_Banda', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n\t\t\t\t\tIF (NEW.participa_Musico != NULL OR NEW.participa_Banda != NULL) THEN\n\t\t\t\t\t\tRETURN NEW;\n\t\t\t\t\tEND IF;\n\t\t\t\t', hash='74d4f5197d7e9c0340e88b1a01bc62d549707318', operation='UPDATE OR INSERT', pgid='pgtrigger_must_have_particpa_musico_or_participa_banda_97de8', table='members_musica', when='BEFORE')),
        ),
    ]
