# Generated by Django 4.1.7 on 2023-05-31 02:35

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_remove_musica_must_have_particpa_musico_or_participa_banda_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='musica',
            name='must_have_particpa_Musico_or_participa_Banda',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='musica',
            trigger=pgtrigger.compiler.Trigger(name='must_have_particpa_Musico_or_participa_Banda', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n\t\t\t\t\tIF (NEW.participa_Musico != NULL) THEN\n\t\t\t\t\t\tRETURN NEW;\n\t\t\t\t\tEND IF;\n\t\t\t\t', hash='f74a0c631fedddb369644a53dddd7b9236ee3b5d', operation='UPDATE OR INSERT', pgid='pgtrigger_must_have_particpa_musico_or_participa_banda_97de8', table='members_musica', when='BEFORE')),
        ),
    ]
