# Generated by Django 4.1.7 on 2023-05-31 02:46

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_remove_musica_must_have_particpa_musico_or_participa_banda_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='musica',
            name='must_have_particpa_Musico_or_participa_Banda',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='musica',
            trigger=pgtrigger.compiler.Trigger(name='teste', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n\t\t\t\t\tIF (NEW.autores != NULL) THEN\n\t\t\t\t\t\tRETURN NEW;\n\t\t\t\t\tEND IF;\n\t\t\t\t', hash='252fa3bd7d18cee9eac133af0e913089f39969c6', operation='UPDATE OR INSERT', pgid='pgtrigger_teste_38c28', table='members_musica', when='BEFORE')),
        ),
    ]
