# Generated by Django 4.1.7 on 2023-05-31 03:40

from django.db import migrations
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_remove_musica_must_have_particpa_musico_or_participa_banda_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='musica',
            name='teste',
        ),
    ]
