# Generated by Django 4.1.7 on 2023-05-31 03:50

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_remove_musica_teste'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='disco',
            name='must_have_disco_musico_or_disco_banda',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='disco',
            trigger=pgtrigger.compiler.Trigger(name='must_have_disco_musico_or_disco_banda', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n\t\t\t\t\tIF (NEW.disco_musico != NULL) THEN\n\t\t\t\t\t\tRETURN NEW;\n\t\t\t\t\tEND IF;\n\t\t\t\t', hash='5ed4b3c13b1efa8a70e6e0239aa293c23119e52f', operation='UPDATE OR INSERT', pgid='pgtrigger_must_have_disco_musico_or_disco_banda_19906', table='members_disco', when='BEFORE')),
        ),
    ]
