# Generated by Django 4.1.7 on 2023-05-31 03:52

from django.db import migrations
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_remove_disco_must_have_disco_musico_or_disco_banda_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='disco',
            name='must_have_disco_musico_or_disco_banda',
        ),
    ]
